# Generated by Django 3.1.2 on 2022-06-06 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actividad', models.CharField(max_length=100, verbose_name='Actividad')),
            ],
            options={
                'verbose_name_plural': 'Actividades',
            },
        ),
    ]
