# Generated by Django 3.1.2 on 2022-06-06 01:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('socios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actividad', models.CharField(max_length=50, verbose_name='Actividad')),
                ('fechapago', models.DateField(verbose_name='Fecha de Pago')),
                ('comprobante', models.CharField(blank=True, max_length=20, null=True, verbose_name='N° Comprobante Pago')),
                ('socio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pago_socio', to='socios.socio')),
            ],
        ),
    ]
