# Generated by Django 3.1.2 on 2022-06-06 01:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('localidades', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Socio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apellido', models.CharField(max_length=50, verbose_name='Apellido')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('dni', models.CharField(max_length=10, verbose_name='DNI')),
                ('fechanacimiento', models.DateField(verbose_name='Fecha de Nacimiento')),
                ('domicilio', models.CharField(max_length=50, verbose_name='Domicilio')),
                ('telefono', models.CharField(max_length=20, verbose_name='Telefono')),
                ('contactoa', models.CharField(max_length=50, verbose_name='Nombre Contacto 1')),
                ('referentea', models.CharField(max_length=50, verbose_name='Telefono Contacto')),
                ('contactob', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nombre Contacto 2')),
                ('referenteb', models.CharField(blank=True, max_length=50, null=True, verbose_name='Telefono Contacto')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-Mail')),
                ('certificadomedico', models.ImageField(blank=True, null=True, upload_to='certificados/', verbose_name='Certificado Medico')),
                ('bucodental', models.ImageField(blank=True, null=True, upload_to='bucodentales/', verbose_name='Certificado Bucodental')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='fotos/', verbose_name='Foto Carnet')),
                ('localidad', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='socio_localidad', to='localidades.localidad')),
            ],
        ),
    ]
