# Generated by Django 3.1.2 on 2022-06-06 01:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('actividades', '0001_initial'),
        ('socios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripcion_actividad', to='actividades.actividad')),
                ('socio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripcion_socio', to='socios.socio')),
            ],
            options={
                'verbose_name_plural': 'Inscripciones',
            },
        ),
    ]
